port/urls.py
from django.urls import path

from . import views

app_name = 'port'
urlpatterns = [
    path('', views.index, name='index'),
    path('submit', views.submit, name='submit'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
      path('port/', include('port.urls')),
]

port/models.py
from django.db import models

# Create your models here.

class Email(models.Model):
    email=models.EmailField(max_length=100,null=True,blank=True)

port/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Email

def index(request):
    return render(request, 'port/index.html')

def submit(request):
    email=request.POST.get('email')
    print("email",email)
    if(email==''):
        return HttpResponse("Enter valid email")
    elif(email is not None):
        e=Email(email=email)
        e.save()
        return render(request, 'port/submit.html')
    else:
        return HttpResponse("Enter valid email")

    

port/templates/port/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submit</title>
</head>
<body>
    <h1>Thanks for connecting . Your Email is saved in my database.</h1>
    <a href="{% url 'port:index' %}">Click to return back</a>
</body>
</html>